
GET http://localhost:4000/

###

GET http://localhost:4000/api/v1/random-number?min=5&max='5'

###

GET http://localhost:4000/api/v1/stringCalculator/@test1 

###

GET http://localhost:4000/api/v1/randomPerson
Content-Type: application/json

{
  "params":["name","age","email","gender"]
}
